services:

  mariadb:
    build: ./requirements/mariadb/
    image: mariadb:Iception
    container_name: mariadb
    env_file:
      - .env
    restart: on-failure
    init: true
    secrets:
      - mariadb_root_password
      - mariadb_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress/
    image: wordpress:Iception
    container_name: wordpress
    env_file:
      - .env
    restart: on-failure
    init: true
    secrets:
      - mariadb_password
      - wordpress_admin_password
      - wordpress_user_password
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    image: nginx:Inception
    container_name: nginx
    env_file:
      - .env
    restart: on-failure
    init: true
    secrets:
      - nginx.crt
      - nginx.key
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html:ro
    networks:
      - inception


  redis:
      build: ./requirements/bonus/redis
      image: redis:Inception
      container_name: redis
      restart: on-failure
      init: true
      networks:
        - inception
  ftp:
    build: ./requirements/bonus/FTP_server
    image: ftp:Inception
    container_name: ftp
    env_file:
      - .env
    ports:
      - "${FTP_PORT}:${FTP_PORT}"
      - "${PASV_PORT}:${PASV_PORT}"
    restart: on-failure
    init: true
    secrets:
      - ftp_password
    volumes:
      - wordpress_data:/var/www/html:rw
    networks:
      - inception

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

networks:
  inception:

secrets:
  nginx.crt:
    file: ./secrets/nginx.crt
  nginx.key:
    file: ./secrets/nginx.key
  mariadb_root_password:
    file: ./secrets/mariadb_root_password
  mariadb_password:
    file: ./secrets/mariadb_password
  wordpress_admin_password:
    file: ./secrets/wordpress_admin_password
  wordpress_user_password:
    file: ./secrets/wordpress_user_password
  ftp_password:
    file: ./secrets/ftp_password