services:
  #MARIADB
  mariadb:
    build:
      context: MariaDB/
      dockerfile: Dockerfile
    image: dbimg:latest
    container_name: db
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_vol:/var/lib/mysql
    networks:
      - wp_net

  # NGINX
  nginx:
    build: NGINX/
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wp_vol:/var/www/
    networks:
      - wp_net

  #wordpress
  wordpress:
    build: WordPress/
    container_name: wp
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - wp_vol:/var/www/
    networks:
      - wp_net


networks:
  wp_net:

volumes:
  wp_vol:
  db_vol:
