[global]
    host access prefix = /host

[plugin:cgroups]
    run script to rename cgroups matching = *docker*
    script to get cgroup names = /usr/libexec/netdata/plugins.d/cgroup-name.sh

[cloud]
    enabled = false

[auth]
    enabled = false

[web]
    bind to = 0.0.0.0
    default port = 19999
    allow connections from = *
    bearer token protection = no
    allow dashboard from = *